app/main/views.py
from flask import Blueprint, render_template, jsonify, url_for, redirect, request, make_response, \
    current_app
from ..models import User, Nurse, Dept
from ..decorators import login_required, login_required_ajax
from datetime import datetime, timedelta

main = Blueprint('main', __name__)

@main.route('/')
def index():
    cookie = request.cookies
    sessionid = cookie.get('sessionid', '')
    user = User.verify_token(sessionid)
    if user:
        return redirect(url_for('nurse.index'))
    return redirect(url_for('.login'))

'''用户登录'''
@main.route('/login', methods=['GET', 'POST'])
def login():
    print(request.args)
    if request.method == 'GET':
        arg = request.args
        if 'alert_msg' in arg:
            alert_msg = arg['alert_msg']
            alert_show = 'true'
        else:
            alert_msg = ''
            alert_show = 'false'
        return render_template('login.html', alert_msg=alert_msg, alert_show=alert_show)
    else:
        data = request.get_json()
        username = data['username']
        password = data['password']
        user = User.query.filter_by(username=username).first()
        if user:
            if user.password == password:
                if user.enable:
                    response = make_response(
                        jsonify({'code': 0, 'data': {'username': username, 'nickname': user.nickname}}))
                    sessionid = user.generate_token()
                    outtime = datetime.today() + timedelta(seconds=current_app.config.get('COOKIE_EXPIRES', 3600))
                    response.set_cookie('sessionid', sessionid, expires=outtime)
                    return response
                else:
                    return jsonify({'code': 10001, 'msg': '该用户已被禁用'})
            else:
                return jsonify({'code': 10000, 'msg': '用户名或密码错误'})
        else:
            return jsonify({'code': 10002, 'msg': '用户不存在'})

'''登出'''
@main.route('/logout')
def logout():
    response = make_response(redirect(url_for('.index')))
    response.delete_cookie('sessionid')
    return response

'''获取科室列表'''
@main.route('/get_dept', methods=['GET'])
@login_required_ajax
def get_dept():
    depts = Dept.query.all()
    data = []
    for item in depts:
        id = item.id
        name = item.dept_name
        data.append({'id': id, 'name': name})
    return jsonify({'code': 0, 'data': data})

app/nurse/views.py
#!/usr/bin/env python
#coding:utf-8

from flask import Blueprint, render_template, jsonify, url_for, redirect, request
from ..models import Nurse, Dept
from .. import db
from ..decorators import login_required, login_required_ajax
from datetime import datetime
import xlrd


nurse = Blueprint('nurse', __name__)

@nurse.route('/', methods=['GET'])
def home():
    return redirect(url_for('.index'))

@nurse.route('/index', methods=['Get'])
@login_required
def index():
    return render_template('nurse/index.html')


'''获取护士列表'''
@nurse.route('/all', methods=['GET'])
@login_required_ajax
def get_all():
    nurses = Nurse.query.all()
    data = []
    for item in nurses:
        emp_sn = item.emp_sn
        name = item.name
        sex = '' if item.sex == None else ('男' if item.sex == 1 else '女')
        dept = item.dept.dept_name if item.dept else None
        data.append({'emp_sn': emp_sn, 'name': name, 'sex': sex, 'dept': dept})
    return jsonify({'code': 0, 'data': data})


@nurse.route('/get_info', methods=['GET'])
@login_required_ajax
def get_info():
    nurses = Nurse.query.order_by(Nurse.emp_sn).all()
    data = [{'emp_sn': item.emp_sn, 'name': item.name, 'dept_id': item.dept_id} for item in nurses]
    return jsonify({'code': 0, 'data': data})

'''获取护士详细信息'''
@nurse.route('/get/<emp_sn>', methods=['GET', 'POST'])
@login_required_ajax
def get_nurse(emp_sn):
    nurse = Nurse.query.filter_by(emp_sn=emp_sn).first()
    if nurse:
        return jsonify({'code': 0, 'data': nurse.to_dict()})
    else:
        return jsonify({'code': 10006, 'msg': '未查到工号为%s的护士' % emp_sn})

'''添加护士'''
@nurse.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'GET':
        return render_template('nurse/addNurse.html')
    data = request.get_json()
    print(data)
    emp_sn = data['emp_sn']
    if Nurse.query.filter_by(emp_sn=emp_sn).all():
        return jsonify({'code': 10003, 'msg': '工号为%s的人员已存在' % emp_sn})
    nurse = Nurse(**data)
    try:
        db.session.add(nurse)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10004, 'msg': str(e)})

'''批量导入'''
@nurse.route('/upload', methods=['POST'])
@login_required_ajax
def upload():
    file = request.files['file']
    f = file.read()
    data = xlrd.open_workbook(file_contents=f)
    names = data.sheet_names()
    filter_name = list(filter(lambda item : item.find('护士信息') > -1, names))
    table_index = names.index(filter_name[0]) if filter_name else 0
    table = data.sheets()[table_index]
    nrows = table.nrows
    ncols = table.ncols
    if ncols < 30:
        return jsonify({'code': 1005, 'msg': '数据表格式不正确'})
    total = nrows - 2
    error_count = 0
    for i in range(2, nrows):
        try:
            row_data = table.row_values(i)
            emp_sn = row_data[2]
            nurse = Nurse.query.filter_by(emp_sn=emp_sn).first()
            if nurse:
                error_count += 1
                continue
            name = row_data[3]
            dept_name = row_data[1]
            dept = Dept.query.filter_by(dept_name=dept_name).first()
            if dept:
                dept_id = dept.id
            else:
                dept = Dept(dept_name=dept_name)
                db.session.add(dept)
                db.session.flush()
                db.session.commit()
                dept_id = dept.id
            sex = 1 if row_data[5] == '男' else 0
            level = row_data[4]
            id_card = row_data[6].strip('\u3000')
            birth_date = datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 7), 0)).strftime('%Y-%m-%d') if table.cell(i, 7).ctype == 3 else row_data[7]
            age = round(row_data[8], 1) if row_data[8] else None
            native = row_data[9]
            nation = row_data[10]
            pre_education = row_data[11]
            pre_school = row_data[12]
            pre_graduate_day = datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 13), 0)).strftime('%Y/%m/%d') if table.cell(i, 13).ctype == 3 else row_data[13]
            pre_professional = row_data[14]
            top_education = row_data[15]
            post_school = row_data[16]
            post_graduate_day = datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 17), 0)).strftime('%Y/%m/%d') if table.cell(i, 17).ctype == 3 else row_data[17]
            post_professional = row_data[18]
            firstjob_day = row_data[19] if table.cell(i, 19).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 19), 0)).strftime('%Y/%m/%d')
            enter_hospital_day = row_data[20] if table.cell(i, 20).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 20), 0)).strftime('%Y/%m/%d')
            top_title = row_data[21]
            get_date = row_data[22] if table.cell(i, 22).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 22), 0)).strftime('%Y/%m/%d')
            end_season = row_data[23] if table.cell(i, 23).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 23), 0)).strftime('%Y/%m/%d')
            work_time = round(row_data[24], 2) if row_data[24] else None
            work_time_divide = row_data[25]
            area = row_data[26]
            post1 = row_data[27]
            post2 = row_data[28]
            status = row_data[29]
            nurse_data = {'emp_sn': emp_sn, 'name': name, 'sex': sex, 'id_card': id_card, 'dept_id': dept_id, 'level': level, 'birth_date': birth_date, 'age': age,
                          'native': native, 'nation': nation, 'pre_education': pre_education, 'pre_school': pre_school, 'pre_graduate_day': pre_graduate_day,
                          'pre_professional': pre_professional, 'top_education': top_education, 'post_school': post_school, 'post_graduate_day': post_graduate_day,
                          'post_professional': post_professional, 'firstjob_day': firstjob_day, 'enter_hospital_day': enter_hospital_day, 'top_title': top_title,
                          'get_date': get_date, 'end_season': end_season, 'work_time': work_time, 'work_time_divide': work_time_divide, 'area': area, 'post1': post1,
                          'post2': post2, 'status': status}
            nurse = Nurse(**nurse_data)
            db.session.add(nurse)
            db.session.commit()
        except Exception as e:
            print(e)
            db.session.rollback()
            error_count += 1
            continue
    return jsonify({'code': 0, 'total': total, 'error_count': error_count, 'success_count': total-error_count})

'''删除护士'''
@nurse.route('/delete', methods=['POST'])
@login_required_ajax
def delete():
    data = request.get_json()
    emps = data['emps']
    try:
        Nurse.query.filter(Nurse.emp_sn.in_(emps)).delete(synchronize_session=False)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10005, 'msg': '删除失败'})

'''获取更新护士信息'''
@nurse.route('/detail/<emp_sn>', methods=['GET', 'POST'])
@login_required
def detail(emp_sn):
    if request.method == 'GET':
        return render_template('nurse/detail.html', emp_sn=emp_sn)
    else:
        data = request.get_json()
        try:
            Nurse.query.filter_by(emp_sn=emp_sn).update(data)
            db.session.commit()
            return jsonify({'code': 0})
        except Exception as e:
            print(e)
            db.session.rollback()
            return jsonify({'code': 10007, 'msg': str(e)})

app/transfer/views.py
#!/usr/bin/env python
#coding:utf-8

from flask import Blueprint, render_template, jsonify, url_for, redirect, request, make_response, \
    current_app
from ..models import User, Nurse, Dept, Transfer
from .. import db
from ..decorators import login_required
from datetime import datetime, timedelta
import json
import time
import xlrd
import math

transfer = Blueprint('transfer', __name__)

@transfer.route('/', methods=['GET'])
@login_required
def home():
    return redirect(url_for('.index'))

@transfer.route('/index', methods=['GET'])
@login_required
def index():
    return render_template('transfer/index.html')

@transfer.route('/get_list', methods=['GET'])
@login_required
def get_list():
    args = request.args
    page = args.get('page', 1, type=int)
    if page <= 0:
        page = 1
    size = args.get('size', 20, type=int)
    search = args.get('search', None)
    data = []
    if search:
        pagination = Transfer.query.filter(Transfer.name.like('%%%s%%' % search)).order_by(Transfer.trans_date.desc(), Transfer.id.desc()).paginate(page, size)
    else:
        pagination = Transfer.query.order_by(Transfer.trans_date.desc(), Transfer.id.desc()).paginate(page, size)
    total = pagination.total
    total_page = pagination.pages
    for item in pagination.items:
        id = item.id
        emp_sn = item.emp_sn
        name = item.name
        outdept = item.outdept.dept_name
        indept = item.indept.dept_name
        trans_date = item.trans_date.strftime('%Y-%m-%d')
        end_date = item.end_date.strftime('%Y-%m-%d') if item.end_date else None
        trans_type = item.trans_type
        remark = item.remark
        data.append({'name': name, 'outdept': outdept, 'indept': indept, 'trans_date': trans_date, 'end_date': end_date,
                     'trans_type': trans_type, 'remark': remark, 'id': id, 'emp_sn': emp_sn})
    return jsonify({'code': 0, 'total': total, 'total_page': total_page, 'currentPage': page, 'pageSize': size, 'data': data})


@transfer.route('/add', methods=['POST'])
@login_required
def add():
    data = request.get_json()
    print(data)
    transfer = Transfer(**data)
    try:
        db.session.add(transfer)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10008, 'msg': str(e)})


@transfer.route('/del', methods=['POST'])
@login_required
def delete():
    data = request.get_json()
    ids = data['ids']
    try:
        Transfer.query.filter(Transfer.id.in_(ids)).delete(synchronize_session=False)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10005, 'msg': str(e)})

app/templates/transfer/index.html
{% extends 'base.html' %}

{% block title %}护理管理信息系统——人员调动{% endblock %}

{% block style %}
    .el-table{
        min-height:350px;
    }
    .el-table__body tr.current-row>td {
        background-color: #ffec8b;
    }
    .el-table--enable-row-hover .el-table__body tr:hover>td{
        background-color: #9FB6CD;
    }
    .el-dialog__header{
        text-align: left !important;
    }
{% endblock %}

{% block  main %}
    <div style="margin-bottom:20px;padding-left:20px;"><strong>人员调动记录列表</strong></div>
    <div class="content-tool">
        <el-input v-model.trim="search" placeholder="按姓名查询" style="display:inline-block;width:300px"></el-input>
        <el-button type="primary" icon="el-icon-search" size="medium" @click="handleSearch">查询</el-button>
        <el-button type="primary" icon="el-icon-plus" size="medium" @click="addClick">添加</el-button>
        <el-button type="primary" icon="el-icon-delete" size="medium" @click="del_trans">删除</el-button>
{#        <el-upload style="display:inline;margin:0 10px;" action="{{ url_for('nurse.upload') }}" class="upload-demo"#}
{#            list-type="text" :show-file-list="false" :before-upload="beforeUpload" :on-progress="uploadProgress"#}
{#            :on-success="uploadSuccess" :on-error="uploadError">#}
{#            <el-button type="primary" icon="el-icon-upload" size="medium" @click="">批量导入</el-button>#}
{#        </el-upload>#}
        <el-button type="primary" icon="el-icon-refresh" size="medium" @click="refresh_table">刷新列表</el-button>
    </div>
    <el-table :data="trans_data" ref="transferList" :header-cell-style="{background:'#eef1f6',color:'#606266'}"
          v-loading="loading" element-loading-text="数据加载中" highlight-current-row>
        <el-table-column type="selection" width="60px" align="center"></el-table-column>
        <el-table-column type="index" width="50"></el-table-column>
        <el-table-column prop="id" label="ID" visible="false" v-if="false"></el-table-column>
        <el-table-column prop="name" label="姓名"></el-table-column>
        <el-table-column prop="outdept" label="出科"></el-table-column>
        <el-table-column prop="indept" label="入科"></el-table-column>
        <el-table-column prop="trans_date" label="调动时间"></el-table-column>
        <el-table-column prop="end_date" label="结束时间"></el-table-column>
        <el-table-column prop="trans_type" label="类别"></el-table-column>
        <el-table-column prop="remark" label="备注" :show-overflow-tooltip="true"></el-table-column>
    </el-table>
    <el-pagination
        @size-change="handleSizeChange"
        @current-change="handleCurrentChange"
        :current-page="currentPage"
        :page-sizes="[20, 50, 100, 200, 500]"
        :page-size="pageSize"
        layout="total,sizes,prev,pager,next,jumper"
        :total="total"
        :page-count="total_page"
    >
    </el-pagination>

    <el-dialog title="添加调动记录" :visible.sync="dialogFormVisible" center @close="closeDialog">
        <el-form :model="addForm" ref="transDataForm" :rules="addFormRules">
            <el-form-item label="姓名：" :label-width="formLabelWidth" prop="name">
                <el-input v-model.trim="addForm.name"></el-input>
            </el-form-item>
            <el-form-item label="出科：" prop="outdept_id" :label-width="formLabelWidth">
                <el-select v-model="addForm.outdept_id">
                    <el-option v-for="item in depts" :key="item.id" :label="item.name" :value="item.id"></el-option>
                </el-select>
            </el-form-item>
            <el-form-item label="入科：" prop="indept_id" :label-width="formLabelWidth">
                <el-select v-model="addForm.indept_id">
                    <el-option v-for="item in depts" :key="item.id" :label="item.name" :value="item.id"></el-option>
                </el-select>
            </el-form-item>
            <el-form-item label="调动时间：" prop="trans_date" :label-width="formLabelWidth">
                <el-date-picker v-model="addForm.trans_date" type="date" value-format="yyyy-MM-dd"></el-date-picker>
            </el-form-item>
            <el-form-item label="结束时间：" prop="end_date" :label-width="formLabelWidth">
                <el-date-picker v-model="addForm.end_date" type="date" value-format="yyyy-MM-dd"></el-date-picker>
            </el-form-item>
            <el-form-item label="类别：" prop="trans_type" :label-width="formLabelWidth">
                <el-select v-model="addForm.trans_type">
                    <el-option v-for="item in types" :key="item" :label="item" :value="item"></el-option>
                </el-select>
            </el-form-item>
            <el-form-item label="备注：" prop="remark" :label-width="formLabelWidth">
                <el-input v-model.trim="addForm.remark"></el-input>
            </el-form-item>
        </el-form>
        <div slot="footer" class="dialog-footer">
            <el-button type="primary" @click="add_trans" :loading="submiting">添加</el-button>
            <el-button type="primary" @click="handleCancel">取消</el-button>
        </div>
    </el-dialog>
{% endblock %}

{% block script %}
axios.defaults.withCredentials=true;
new Vue({
    el: '#app',
    delimiters: ['{[', ']}'],
    data: {
        search: '',
        nickname: JSON.parse(window.sessionStorage.getItem('user_info')).nickname,
        trans_data: [],
        addForm: {
            name: null,
            outdept_id: null,
            indept_id: null,
            trans_date: null,
            end_date: null,
            trans_type: null,
            remark: null,
        },
        dialogFormVisible: false,
        formLabelWidth: '120px',
        depts: {},
        types: ['调动', '临时借调', '其他'],
        addFormRules: {
            name: [{required: true, message: '请输入姓名', trigger: 'blur'}],
            outdept_id: [{required: true, message: '请选择出科科室', trigger: 'blur'}],
            indept_id: [{required: true, message: '请选择入科科室', trigger: 'blur'}],
            trans_date: [{required: true, message: '请选择调动时间', trigger: 'blur'}]
        },
        submiting: false,
        loading: false,
        currentPage: 1,
        pageSize: 20,
        total: 0,
        total_page: 0,
        loadObject: null,
    },
    methods: {
        //获取调动记录列表
        get_data(page, size){
            axios({
                method: 'get',
                url: '{{ url_for("transfer.get_list") }}',
                params: {page: page, size: size, search: this.search},
            }).then(response => {
                this.loading = true
                console.log(response)
                if(response.data.code == 0){
                    this.trans_data = response.data.data
                    this.total = response.data.total
                    this.total_page = response.data.total_page
                    this.currentPage = response.data.currentPage
                    this.pageSize = response.data.pageSize
                }else{
                    this.$message.error('获取调动记录列表失败')
                }
                this.loading = false
            }).catch(response => {
                this.loading = false
                this.$message.error('获取调动记录列表请求失败，请稍后重试或联系管理员')
            })
        },
        //获取可是列表
        get_depts(){
            axios({
                method: 'get',
                url: '{{ url_for("main.get_dept") }}'
            }).then(response =>{
                if(response.data.code == 0){
                    this.depts = response.data.data
                }else{
                    this.$message.error('获取科室列表失败')
                }
            }).catch(response => {
                this.$message.error('获取科室列表失败')
            })
        },
        //搜索
        handleSearch(){
            this.get_data(1, this.pageSize)
        },
        //刷新列表
        refresh_table(){
            this.search = ''
            this.get_data(1, this.pageSize)
        },
        //点击添加按钮
        addClick(){
            this.dialogFormVisible = true
            this.get_depts()
        },
        //添加记录
        add_trans(){
            this.$refs.transDataForm.validate(valid =>{
                if(valid){
                    this.submiting = true
                    axios({
                        method: 'post',
                        url: '{{ url_for("transfer.add") }}',
                        data: this.addForm,
                        headers: {'Content-Type': 'application/json'}
                    }).then(response => {
                        console.log(response)
                        if(response.data.code == 0){
                            this.$message.success('添加成功')
                            this.$refs.transDataForm.resetFields()
                        }else{
                            this.$message.error('添加失败，msg:' + response.data.msg)
                        }
                    }).catch(response => {
                        this.$message.error('添加失败，请稍后重试或联系管理员')
                    })
                    this.submiting = false
                }else{
                    console.log('数据验证错误')
                }
            })
        },
        //取消
        handleCancel(){
            this.$refs.transDataForm.resetFields()
            this.dialogFormVisible=false
        },
        //关闭dialog
        closeDialog(){
            this.refresh_table()
        },
        //删除
        del_trans(){
            let ids = []
            this.$refs.transferList.selection.map(item => ids.push(item.id))
            if(ids.length == 0){
                this.$message({
                    showClose: true,
                    message:'请选择要删除的记录',
                    type: 'warning'
                })
                return
            }
            axios({
                method: 'post',
                url: '{{ url_for("transfer.delete") }}',
                data: {ids: ids}
            }).then(response => {
                if(response.data.code == 0){
                    this.$message.success('删除成功')
                    this.refresh_table()
                }else{
                    this.$message.error('删除失败, msg:' + response.data.msg)
                }
            }).catch(response => {
                this.$message.error('删除失败，请联系管理员或稍后重试')
            })
        },
{#        beforeUpload(file){#}
{#            let filetype = file.type#}
{#            console.log(filetype)#}
{#            types = [#}
{#                'application/vnd.ms-excel',#}
{#                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'#}
{#            ]#}
{#            if(types.indexOf(filetype) == -1){#}
{#                this.$message({#}
{#                    type: 'error',#}
{#                    message: '文件类型不正确，请重新选择',#}
{#                    showClose: true#}
{#                })#}
{#                return false#}
{#            }else{#}
{#                return true#}
{#            }#}
{#        },#}
{#        uploadProgress(){#}
{#            this.loadObject = this.$loading({#}
{#                lock: true,#}
{#                text: '正在导入，请稍候',#}
{#                spinner: 'el-icon-loading',#}
{#                background: 'rgba(0,0,0,0.7)'#}
{#            })#}
{#        },#}
{#        uploadSuccess(res, file){#}
{#            console.log(res)#}
{#            console.log(file)#}
{#            this.loadObject.close()#}
{#            if(res['code'] != 0){#}
{#                this.$message({#}
{#                    type: 'error',#}
{#                    message: res['msg'],#}
{#                    showClose: true#}
{#                })#}
{#            }else{#}
{#                this.$message({#}
{#                    type: 'success',#}
{#                    message:'总共'+res['total']+'条，成功'+res['success_count']+'条，失败'+res['error_count']+'条',#}
{#                    showClose: true,#}
{#                })#}
{#                this.get_nurses()#}
{#            }#}
{#        },#}
{#        uploadError(res, file){#}
{#            console.log(res)#}
{#            console.log(file)#}
{#            this.loadObject.close()#}
{#            this.$message.error('导入失败，请稍后重试')#}
{#        },#}

        handleSizeChange(val){
            let total_page = Math.ceil(this.total / val)
            if(this.currentPage>total_page){
                this.currentPage = total_page
            }
            this.get_data(this.currentPage, val)
        },
        handleCurrentChange(val){
            this.get_data(val, this.pageSize)
        },
    },
    mounted(){
        this.get_data(this.currentPage, this.pageSize)
    }
})
{% endblock %}