app/nurse/__init__.py
#!/usr/bin/env python
#coding:utf-8

app/nurse/views.py
#!/usr/bin/env python
#coding:utf-8

from flask import Blueprint, render_template, jsonify, url_for, redirect, request
from ..models import Nurse, Dept
from .. import db
from ..decorators import login_required, login_required_ajax
from datetime import datetime
import xlrd


nurse = Blueprint('nurse', __name__)

@nurse.route('/', methods=['GET'])
def home():
    return redirect(url_for('.index'))

@nurse.route('/index', methods=['Get'])
@login_required
def index():
    return render_template('nurse/index.html')


'''获取护士列表'''
@nurse.route('/all', methods=['GET'])
@login_required_ajax
def get_all():
    nurses = Nurse.query.all()
    data = []
    for item in nurses:
        emp_sn = item.emp_sn
        name = item.name
        sex = '' if item.sex == None else ('男' if item.sex == 1 else '女')
        dept = item.dept.dept_name if item.dept else None
        data.append({'emp_sn': emp_sn, 'name': name, 'sex': sex, 'dept': dept})
    return jsonify({'code': 0, 'data': data})


@nurse.route('/get_info', methods=['GET'])
@login_required_ajax
def get_info():
    nurses = Nurse.query.order_by(Nurse.emp_sn).all()
    data = [{'emp_sn': item.emp_sn, 'name': item.name, 'dept_id': item.dept_id} for item in nurses]
    return jsonify({'code': 0, 'data': data})

'''获取护士详细信息'''
@nurse.route('/get/<emp_sn>', methods=['GET', 'POST'])
@login_required_ajax
def get_nurse(emp_sn):
    nurse = Nurse.query.filter_by(emp_sn=emp_sn).first()
    if nurse:
        return jsonify({'code': 0, 'data': nurse.to_dict()})
    else:
        return jsonify({'code': 10006, 'msg': '未查到工号为%s的护士' % emp_sn})

'''添加护士'''
@nurse.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'GET':
        return render_template('nurse/addNurse.html')
    data = request.get_json()
    print(data)
    emp_sn = data['emp_sn']
    if Nurse.query.filter_by(emp_sn=emp_sn).all():
        return jsonify({'code': 10003, 'msg': '工号为%s的人员已存在' % emp_sn})
    nurse = Nurse(**data)
    try:
        db.session.add(nurse)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10004, 'msg': str(e)})

'''批量导入'''
@nurse.route('/upload', methods=['POST'])
@login_required_ajax
def upload():
    file = request.files['file']
    f = file.read()
    data = xlrd.open_workbook(file_contents=f)
    names = data.sheet_names()
    filter_name = list(filter(lambda item : item.find('护士信息') > -1, names))
    table_index = names.index(filter_name[0]) if filter_name else 0
    table = data.sheets()[table_index]
    nrows = table.nrows
    ncols = table.ncols
    if ncols < 30:
        return jsonify({'code': 1005, 'msg': '数据表格式不正确'})
    total = nrows - 2
    error_count = 0
    for i in range(2, nrows):
        try:
            row_data = table.row_values(i)
            emp_sn = row_data[2]
            nurse = Nurse.query.filter_by(emp_sn=emp_sn).first()
            if nurse:
                error_count += 1
                continue
            name = row_data[3]
            dept_name = row_data[1]
            dept = Dept.query.filter_by(dept_name=dept_name).first()
            if dept:
                dept_id = dept.id
            else:
                dept = Dept(dept_name=dept_name)
                db.session.add(dept)
                db.session.flush()
                db.session.commit()
                dept_id = dept.id
            sex = 1 if row_data[5] == '男' else 0
            level = row_data[4]
            id_card = row_data[6].strip('\u3000')
            birth_date = datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 7), 0)).strftime('%Y-%m-%d') if table.cell(i, 7).ctype == 3 else row_data[7]
            age = round(row_data[8], 1) if row_data[8] else None
            native = row_data[9]
            nation = row_data[10]
            pre_education = row_data[11]
            pre_school = row_data[12]
            pre_graduate_day = datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 13), 0)).strftime('%Y/%m/%d') if table.cell(i, 13).ctype == 3 else row_data[13]
            pre_professional = row_data[14]
            top_education = row_data[15]
            post_school = row_data[16]
            post_graduate_day = datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 17), 0)).strftime('%Y/%m/%d') if table.cell(i, 17).ctype == 3 else row_data[17]
            post_professional = row_data[18]
            firstjob_day = row_data[19] if table.cell(i, 19).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 19), 0)).strftime('%Y/%m/%d')
            enter_hospital_day = row_data[20] if table.cell(i, 20).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 20), 0)).strftime('%Y/%m/%d')
            top_title = row_data[21]
            get_date = row_data[22] if table.cell(i, 22).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 22), 0)).strftime('%Y/%m/%d')
            end_season = row_data[23] if table.cell(i, 23).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 23), 0)).strftime('%Y/%m/%d')
            work_time = round(row_data[24], 2) if row_data[24] else None
            work_time_divide = row_data[25]
            area = row_data[26]
            post1 = row_data[27]
            post2 = row_data[28]
            status = row_data[29]
            nurse_data = {'emp_sn': emp_sn, 'name': name, 'sex': sex, 'id_card': id_card, 'dept_id': dept_id, 'level': level, 'birth_date': birth_date, 'age': age,
                          'native': native, 'nation': nation, 'pre_education': pre_education, 'pre_school': pre_school, 'pre_graduate_day': pre_graduate_day,
                          'pre_professional': pre_professional, 'top_education': top_education, 'post_school': post_school, 'post_graduate_day': post_graduate_day,
                          'post_professional': post_professional, 'firstjob_day': firstjob_day, 'enter_hospital_day': enter_hospital_day, 'top_title': top_title,
                          'get_date': get_date, 'end_season': end_season, 'work_time': work_time, 'work_time_divide': work_time_divide, 'area': area, 'post1': post1,
                          'post2': post2, 'status': status}
            nurse = Nurse(**nurse_data)
            db.session.add(nurse)
            db.session.commit()
        except Exception as e:
            print(e)
            db.session.rollback()
            error_count += 1
            continue
    return jsonify({'code': 0, 'total': total, 'error_count': error_count, 'success_count': total-error_count})

'''删除护士'''
@nurse.route('/delete', methods=['POST'])
@login_required_ajax
def delete():
    data = request.get_json()
    emps = data['emps']
    try:
        Nurse.query.filter(Nurse.emp_sn.in_(emps)).delete(synchronize_session=False)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10005, 'msg': '删除失败'})

'''获取更新护士信息'''
@nurse.route('/detail/<emp_sn>', methods=['GET', 'POST'])
@login_required
def detail(emp_sn):
    if request.method == 'GET':
        return render_template('nurse/detail.html', emp_sn=emp_sn)
    else:
        data = request.get_json()
        try:
            Nurse.query.filter_by(emp_sn=emp_sn).update(data)
            db.session.commit()
            return jsonify({'code': 0})
        except Exception as e:
            print(e)
            db.session.rollback()
            return jsonify({'code': 10007, 'msg': str(e)})

app/templates/nurse/index.html
{% extends 'base.html' %}

{% block title %}护理管理信息系统{% endblock %}

{% block style %}
    .el-table{
        min-height:350px;
    }
    .el-table__body tr.current-row>td {
        background-color: #ffec8b;
    }
    .el-table--enable-row-hover .el-table__body tr:hover>td{
        background-color: #9FB6CD;
    }
{% endblock %}

{% block  main %}
    <div style="margin-bottom:20px;padding-left:20px;"><strong>护理人员列表</strong></div>
    <div class="content-tool">
        <el-input v-model="search" placeholder="请输入搜索内容" style="display:inline-block;width:300px"></el-input>
        <el-button type="primary" icon="el-icon-search" size="medium" @click="handleSearch">查询</el-button>
        <el-button type="primary" icon="el-icon-plus" size="medium" @click="add_nurse">添加</el-button>
        <el-button type="primary" icon="el-icon-delete" size="medium" @click="del_nurse">删除</el-button>
        <el-upload style="display:inline;margin:0 10px;" action="{{ url_for('nurse.upload') }}" class="upload-demo"
            list-type="text" :show-file-list="false" :before-upload="beforeUpload" :on-progress="uploadProgress"
            :on-success="uploadSuccess" :on-error="uploadError">
            <el-button type="primary" icon="el-icon-upload" size="medium" @click="">批量导入</el-button>
        </el-upload>
        <el-button type="primary" icon="el-icon-refresh" size="medium" @click="refresh_table">刷新列表</el-button>
    </div>
    <el-table :data="page_data" ref="nurseList" :header-cell-style="{background:'#eef1f6',color:'#606266'}"
          v-loading="loading" element-loading-text="数据加载中" highlight-current-row
         :default-sort="{prop: sort_prop, order: sort_order}" @sort-change="handleSortChange">
        <el-table-column type="selection" width="60px" align="center"></el-table-column>
        <el-table-column type="index" width="50"></el-table-column>
        <el-table-column prop="emp_sn" label="工号" sortable="custom">
            <template slot-scope="scope">
                <a :href="'/huli/nurse/detail/'+ scope.row.emp_sn">{[ scope.row.emp_sn ]}</a>
            </template>
        </el-table-column>
        <el-table-column prop="name" label="姓名" sortable="custom"></el-table-column>
        <el-table-column prop="sex" label="性别" sortable="custom"></el-table-column>
        <el-table-column prop="dept" label="科室" sortable="custom"></el-table-column>
    </el-table>
    <el-pagination
        @size-change="handleSizeChange"
        @current-change="handleCurrentChange"
        :current-page="currentPage"
        :page-sizes="[20, 50, 100, 200, 500]"
        :page-size="pageSize"
        layout="total,sizes,prev,pager,next,jumper"
        :total="total"
        :page-count="total_page"
    >
    </el-pagination>
{% endblock %}

{% block script %}
axios.defaults.withCredentials=true;
new Vue({
    el: '#app',
    delimiters: ['{[', ']}'],
    data: {
        search: '',
        nickname: JSON.parse(window.sessionStorage.getItem('user_info')).nickname,
        nurses: [],
        filter_nurses: [],
        loading: true,
        sort_prop: 'emp_sn',
        sort_order: 'ascending',
        currentPage: 1,
        pageSize: 20,
        total: 0,
        total_page: 0,
        page_data: [],
        loadObject: null,
    },
    methods: {
        get_nurses(){
            axios({
                method: 'get',
                url: '{{ url_for("nurse.get_all") }}'
            }).then(response => {
                this.loading = false
                if(response.data.code == 0){
                    this.nurses = response.data.data
                    this.filter_nurses = this.nurses
                    if(this.sort_order == 'ascending'){
                        if(this.sort_prop == 'emp_sn'){
                            this.nurses.sort((a, b) => {return a[this.sort_prop] - b[this.sort_prop]})
                        }else{
                            this.nurses.sort((a, b) => {return a[this.sort_prop].localeCompare(b[this.sort_prop],'zh-CN')})
                        }
                    }else{
                        if(this.sort_prop == 'emp_sn'){
                            this.nurses.sort((a, b) => {return b[this.sort_prop] - a[this.sort_prop]})
                        }else{
                            this.nurses.sort((a,b) => {return b[this.sort_prop].localeCompare(a[this.sort_prop],'zh-CN')})
                        }
                    }
                    this.page_data = this.nurses.slice(0, this.pageSize)
                    this.currentPage = 1
                    this.total = this.nurses.length
                    this.total_page = Math.ceil(this.total / this.pageSize)
                }
            }).catch(response => {
                this.loading = false
                this.$message.error('获取护理人员列表失败')
            })

        },
        handleSearch(){
            this.filter_nurses = this.nurses.filter(data => {
                return Object.keys(data).some(key => {
                    return String(data[key]).toLowerCase().indexOf(this.search) > -1
                })
            })
            this.currentPage = 1
            this.page_data = this.filter_nurses.slice(0, this.pageSize)
            this.total = this.filter_nurses.length
            this.total_page = Math.ceil(this.total / this.pageSize)
        },
        add_nurse(){
            window.location.assign('{{ url_for("nurse.add") }}')
        },
        del_nurse(){
            let emps = []
            this.$refs.nurseList.selection.map(item => emps.push(item.emp_sn))
            if(emps.length == 0){
                this.$message({
                    showClose: true,
                    message:'请选择要删除的人员',
                    type: 'warning'
                })
                return
            }
            axios({
                method: 'post',
                url: '{{ url_for("nurse.delete") }}',
                data: {emps: emps}
            }).then(response => {
                if(response.data.code == 0){
                    this.get_nurses()
                    this.$message.success('删除成功')
                }else{
                    this.$message.error('删除失败')
                }
            }).catch(response => {
                this.$message.error('删除失败')
            })
        },
        beforeUpload(file){
            let filetype = file.type
            console.log(filetype)
            types = [
                'application/vnd.ms-excel',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
            ]
            if(types.indexOf(filetype) == -1){
                this.$message({
                    type: 'error',
                    message: '文件类型不正确，请重新选择',
                    showClose: true
                })
                return false
            }else{
                return true
            }
        },
        uploadProgress(){
            this.loadObject = this.$loading({
                lock: true,
                text: '正在导入，请稍候',
                spinner: 'el-icon-loading',
                background: 'rgba(0,0,0,0.7)'
            })
        },
        uploadSuccess(res, file){
            console.log(res)
            console.log(file)
            this.loadObject.close()
            if(res['code'] != 0){
                this.$message({
                    type: 'error',
                    message: res['msg'],
                    showClose: true
                })
            }else{
                this.$message({
                    type: 'success',
                    message:'总共'+res['total']+'条，成功'+res['success_count']+'条，失败'+res['error_count']+'条',
                    showClose: true,
                })
                this.get_nurses()
            }
        },
        uploadError(res, file){
            console.log(res)
            console.log(file)
            this.loadObject.close()
            this.$message.error('导入失败，请稍后重试')
        },
        refresh_table(){
            this.loading = true
            this.search = ''
            this.get_nurses()
        },
        handleSizeChange(val){
            let total_page = Math.ceil(this.total / val)
            if(this.currentPage>total_page){
                this.currentPage = total_page
            }
            this.pageSize = val
            this.page_data = this.filter_nurses.slice((this.currentPage-1)*val, this.currentPage*val)
        },
        handleCurrentChange(val){
            this.currentPage = val
            this.page_data = this.filter_nurses.slice((val-1)*this.pageSize, val*this.pageSize)
        },
        handleSortChange(column){
            let sort_prop = column.prop
            let sort_order = column.order
            this.sort_prop = sort_prop
            this.sort_order = sort_order

            //先根据排序规则排序
            if(this.sort_order == 'ascending'){
                if(this.sort_prop == 'emp_sn'){
                    this.nurses.sort((a, b) => {return a[this.sort_prop] - b[this.sort_prop]})
                }else{
                    this.nurses.sort((a, b) => {return a[this.sort_prop].localeCompare(b[this.sort_prop],'zh-CN')})
                }
            }else{
                if(this.sort_prop == 'emp_sn'){
                    this.nurses.sort((a, b) => {return b[this.sort_prop] - a[this.sort_prop]})
                }else{
                    this.nurses.sort((a,b) => {return b[this.sort_prop].localeCompare(a[this.sort_prop],'zh-CN')})
                }
            }

            //如果有搜索，再将数据筛选出来
            this.filter_nurses = this.nurses.filter(data => {
                return Object.keys(data).some(key => {
                    return String(data[key]).toLowerCase().indexOf(this.search) > -1
                })
            })
            this.currentPage = 1
            this.page_data = this.filter_nurses.slice(0, this.pageSize)
        }
    },
    mounted(){
        this.get_nurses()
    }
})
{% endblock %}