app/leave/views.py
#!/usr/bin/env python
#coding:utf-8

from flask import Blueprint, render_template, jsonify, url_for, redirect, request
from ..models import Leave
from .. import db
from ..decorators import login_required, login_required_ajax


leave = Blueprint('leave', __name__)

@leave.route('/', methods=['GET'])
@login_required
def home():
    return redirect(url_for('.index'))

@leave.route('/index', methods=['GET'])
@login_required
def index():
    return render_template('leave/index.html')

@leave.route('/get_list', methods=['GET'])
@login_required_ajax
def get_list():
    args = request.args
    page = args.get('page', 1, type=int)
    if page <= 0:
        page = 1
    size = args.get('size', 20, type=int)
    search = args.get('search', None)
    data = []
    if search:
        pagination = Leave.query.filter(Leave.name.like('%%%s%%' % search)).order_by(Leave.id.desc()).paginate(page, size)
    else:
        pagination = Leave.query.order_by(Leave.id.desc()).paginate(page, size)

    total = pagination.total
    total_page = pagination.pages
    for item in pagination.items:
        id = item.id
        emp_sn = item.emp_sn
        name = item.name
        dept = item.dept.dept_name
        time_start = item.time_start.strftime('%Y-%m-%d %H:%M:%S')
        time_end = item.time_end.strftime('%Y-%m-%d %H:%M:%S')
        days = item.days
        leave_type = item.leave_type
        remark = item.remark
        data.append({'id': id, 'emp_sn': emp_sn, 'name': name, 'dept': dept, 'time_start': time_start,
                     'time_end': time_end, 'days':days, 'leave_type': leave_type, 'remark': remark})
    return jsonify({'code': 0, 'total': total, 'total_page': total_page, 'currentPage': page, 'pageSize': size, 'data': data})


@leave.route('/add', methods=['POST'])
@login_required_ajax
def add():
    data = request.get_json()
    print(data)
    leave = Leave(**data)
    try:
        db.session.add(leave)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10008, 'msg': str(e)})


@leave.route('/del', methods=['POST'])
@login_required_ajax
def delete():
    data = request.get_json()
    ids = data['ids']
    try:
        Leave.query.filter(Leave.id.in_(ids)).delete(synchronize_session=False)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10005, 'msg': str(e)})

app/nurse/views.py
#!/usr/bin/env python
#coding:utf-8

from flask import Blueprint, render_template, jsonify, url_for, redirect, request
from ..models import Nurse, Dept
from .. import db
from ..decorators import login_required, login_required_ajax
from datetime import datetime
import xlrd


nurse = Blueprint('nurse', __name__)

@nurse.route('/', methods=['GET'])
def home():
    return redirect(url_for('.index'))

@nurse.route('/index', methods=['Get'])
@login_required
def index():
    return render_template('nurse/index.html')


'''获取护士列表'''
@nurse.route('/all', methods=['GET'])
@login_required_ajax
def get_all():
    nurses = Nurse.query.all()
    data = []
    for item in nurses:
        emp_sn = item.emp_sn
        name = item.name
        sex = '' if item.sex == None else ('男' if item.sex == 1 else '女')
        dept = item.dept.dept_name if item.dept else None
        data.append({'emp_sn': emp_sn, 'name': name, 'sex': sex, 'dept': dept})
    return jsonify({'code': 0, 'data': data})


@nurse.route('/get_info', methods=['GET'])
@login_required_ajax
def get_info():
    nurses = Nurse.query.order_by(Nurse.emp_sn).all()
    data = [{'emp_sn': item.emp_sn, 'name': item.name, 'dept_id': item.dept_id} for item in nurses]
    return jsonify({'code': 0, 'data': data})

'''获取护士详细信息'''
@nurse.route('/get/<emp_sn>', methods=['GET', 'POST'])
@login_required_ajax
def get_nurse(emp_sn):
    nurse = Nurse.query.filter_by(emp_sn=emp_sn).first()
    if nurse:
        return jsonify({'code': 0, 'data': nurse.to_dict()})
    else:
        return jsonify({'code': 10006, 'msg': '未查到工号为%s的护士' % emp_sn})

'''添加护士'''
@nurse.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'GET':
        return render_template('nurse/addNurse.html')
    data = request.get_json()
    print(data)
    emp_sn = data['emp_sn']
    if Nurse.query.filter_by(emp_sn=emp_sn).all():
        return jsonify({'code': 10003, 'msg': '工号为%s的人员已存在' % emp_sn})
    nurse = Nurse(**data)
    try:
        db.session.add(nurse)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10004, 'msg': str(e)})

'''批量导入'''
@nurse.route('/upload', methods=['POST'])
@login_required_ajax
def upload():
    file = request.files['file']
    f = file.read()
    data = xlrd.open_workbook(file_contents=f)
    names = data.sheet_names()
    filter_name = list(filter(lambda item : item.find('护士信息') > -1, names))
    table_index = names.index(filter_name[0]) if filter_name else 0
    table = data.sheets()[table_index]
    nrows = table.nrows
    ncols = table.ncols
    if ncols < 30:
        return jsonify({'code': 1005, 'msg': '数据表格式不正确'})
    total = nrows - 2
    error_count = 0
    for i in range(2, nrows):
        try:
            row_data = table.row_values(i)
            emp_sn = row_data[2]
            nurse = Nurse.query.filter_by(emp_sn=emp_sn).first()
            if nurse:
                error_count += 1
                continue
            name = row_data[3]
            dept_name = row_data[1]
            dept = Dept.query.filter_by(dept_name=dept_name).first()
            if dept:
                dept_id = dept.id
            else:
                dept = Dept(dept_name=dept_name)
                db.session.add(dept)
                db.session.flush()
                db.session.commit()
                dept_id = dept.id
            sex = 1 if row_data[5] == '男' else 0
            level = row_data[4]
            id_card = row_data[6].strip('\u3000')
            birth_date = datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 7), 0)).strftime('%Y-%m-%d') if table.cell(i, 7).ctype == 3 else row_data[7]
            age = round(row_data[8], 1) if row_data[8] else None
            native = row_data[9]
            nation = row_data[10]
            pre_education = row_data[11]
            pre_school = row_data[12]
            pre_graduate_day = datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 13), 0)).strftime('%Y/%m/%d') if table.cell(i, 13).ctype == 3 else row_data[13]
            pre_professional = row_data[14]
            top_education = row_data[15]
            post_school = row_data[16]
            post_graduate_day = datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 17), 0)).strftime('%Y/%m/%d') if table.cell(i, 17).ctype == 3 else row_data[17]
            post_professional = row_data[18]
            firstjob_day = row_data[19] if table.cell(i, 19).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 19), 0)).strftime('%Y/%m/%d')
            enter_hospital_day = row_data[20] if table.cell(i, 20).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 20), 0)).strftime('%Y/%m/%d')
            top_title = row_data[21]
            get_date = row_data[22] if table.cell(i, 22).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 22), 0)).strftime('%Y/%m/%d')
            end_season = row_data[23] if table.cell(i, 23).ctype != 3 else datetime(*xlrd.xldate_as_tuple(table.cell_value(i, 23), 0)).strftime('%Y/%m/%d')
            work_time = round(row_data[24], 2) if row_data[24] else None
            work_time_divide = row_data[25]
            area = row_data[26]
            post1 = row_data[27]
            post2 = row_data[28]
            status = row_data[29]
            nurse_data = {'emp_sn': emp_sn, 'name': name, 'sex': sex, 'id_card': id_card, 'dept_id': dept_id, 'level': level, 'birth_date': birth_date, 'age': age,
                          'native': native, 'nation': nation, 'pre_education': pre_education, 'pre_school': pre_school, 'pre_graduate_day': pre_graduate_day,
                          'pre_professional': pre_professional, 'top_education': top_education, 'post_school': post_school, 'post_graduate_day': post_graduate_day,
                          'post_professional': post_professional, 'firstjob_day': firstjob_day, 'enter_hospital_day': enter_hospital_day, 'top_title': top_title,
                          'get_date': get_date, 'end_season': end_season, 'work_time': work_time, 'work_time_divide': work_time_divide, 'area': area, 'post1': post1,
                          'post2': post2, 'status': status}
            nurse = Nurse(**nurse_data)
            db.session.add(nurse)
            db.session.commit()
        except Exception as e:
            print(e)
            db.session.rollback()
            error_count += 1
            continue
    return jsonify({'code': 0, 'total': total, 'error_count': error_count, 'success_count': total-error_count})

'''删除护士'''
@nurse.route('/delete', methods=['POST'])
@login_required_ajax
def delete():
    data = request.get_json()
    emps = data['emps']
    try:
        Nurse.query.filter(Nurse.emp_sn.in_(emps)).delete(synchronize_session=False)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10005, 'msg': '删除失败'})

'''获取更新护士信息'''
@nurse.route('/detail/<emp_sn>', methods=['GET', 'POST'])
@login_required
def detail(emp_sn):
    if request.method == 'GET':
        return render_template('nurse/detail.html', emp_sn=emp_sn)
    else:
        data = request.get_json()
        try:
            Nurse.query.filter_by(emp_sn=emp_sn).update(data)
            db.session.commit()
            return jsonify({'code': 0})
        except Exception as e:
            print(e)
            db.session.rollback()
            return jsonify({'code': 10007, 'msg': str(e)})

app/train/views.py
#!/usr/bin/env python
#coding:utf-8

from flask import Blueprint, render_template, jsonify, url_for, redirect, request
from ..models import Train
from .. import db
from ..decorators import login_required, login_required_ajax


train = Blueprint('train', __name__)

@train.route('/')
@login_required
def home():
    pass

@train.route('/index')
@login_required
def index():
    return render_template('train/index.html')

@train.route('/get_list', methods=['GET'])
@login_required_ajax
def get_list():
    args = request.args
    page = args.get('page', 1, type=int)
    if page <= 0:
        page = 1
    size = args.get('size', 20, type=int)
    search = args.get('search', None)
    data = []
    if search:
        pagination = Train.query.filter(Train.name.like('%%%s%%' % search)).order_by(Train.id.desc()).paginate(page, size)
    else:
        pagination = Train.query.order_by(Train.id.desc()).paginate(page, size)

    total = pagination.total
    total_page = pagination.pages
    for item in pagination.items:
        id = item.id
        emp_sn = item.emp_sn
        name = item.name
        dept = item.dept.dept_name
        date_start = item.date_start.strftime('%Y-%m-%d')
        date_end = item.date_end.strftime('%Y-%m-%d')
        train_name = item.train_name
        place = item.place
        fee = item.fee
        remark = item.remark
        data.append({'id': id, 'emp_sn': emp_sn, 'name': name, 'dept': dept, 'date_start': date_start,
                     'date_end': date_end, 'train_name':train_name, 'place': place, 'fee': fee, 'remark': remark})
    return jsonify({'code': 0, 'total': total, 'total_page': total_page, 'currentPage': page, 'pageSize': size, 'data': data})


@train.route('/add', methods=['POST'])
@login_required_ajax
def add():
    data = request.get_json()
    print(data)
    train = Train(**data)
    try:
        db.session.add(train)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10008, 'msg': str(e)})


@train.route('/del', methods=['POST'])
@login_required_ajax
def delete():
    data = request.get_json()
    ids = data['ids']
    try:
        Train.query.filter(Train.id.in_(ids)).delete(synchronize_session=False)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10005, 'msg': str(e)})

app/transfer/views.py
#!/usr/bin/env python
#coding:utf-8

from flask import Blueprint, render_template, jsonify, url_for, redirect, request, make_response, \
    current_app
from ..models import User, Nurse, Dept, Transfer
from .. import db
from ..decorators import login_required
from datetime import datetime, timedelta
import json
import time
import xlrd
import math

transfer = Blueprint('transfer', __name__)

@transfer.route('/', methods=['GET'])
@login_required
def home():
    return redirect(url_for('.index'))

@transfer.route('/index', methods=['GET'])
@login_required
def index():
    return render_template('transfer/index.html')

@transfer.route('/get_list', methods=['GET'])
@login_required
def get_list():
    args = request.args
    page = args.get('page', 1, type=int)
    if page <= 0:
        page = 1
    size = args.get('size', 20, type=int)
    search = args.get('search', None)
    data = []
    if search:
        pagination = Transfer.query.filter(Transfer.name.like('%%%s%%' % search)).order_by(Transfer.trans_date.desc(), Transfer.id.desc()).paginate(page, size)
    else:
        pagination = Transfer.query.order_by(Transfer.trans_date.desc(), Transfer.id.desc()).paginate(page, size)
    total = pagination.total
    total_page = pagination.pages
    for item in pagination.items:
        id = item.id
        emp_sn = item.emp_sn
        name = item.name
        outdept = item.outdept.dept_name
        indept = item.indept.dept_name
        trans_date = item.trans_date.strftime('%Y-%m-%d')
        end_date = item.end_date.strftime('%Y-%m-%d') if item.end_date else None
        trans_type = item.trans_type
        remark = item.remark
        data.append({'name': name, 'outdept': outdept, 'indept': indept, 'trans_date': trans_date, 'end_date': end_date,
                     'trans_type': trans_type, 'remark': remark, 'id': id, 'emp_sn': emp_sn})
    return jsonify({'code': 0, 'total': total, 'total_page': total_page, 'currentPage': page, 'pageSize': size, 'data': data})


@transfer.route('/add', methods=['POST'])
@login_required
def add():
    data = request.get_json()
    print(data)
    transfer = Transfer(**data)
    try:
        db.session.add(transfer)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10008, 'msg': str(e)})


@transfer.route('/del', methods=['POST'])
@login_required
def delete():
    data = request.get_json()
    ids = data['ids']
    try:
        Transfer.query.filter(Transfer.id.in_(ids)).delete(synchronize_session=False)
        db.session.commit()
        return jsonify({'code': 0})
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'code': 10005, 'msg': str(e)})

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}护理管理信息系统{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/element-ui@2.12.0.css') }}">
    <style>
        *{
            margin: 0px;
            padding:0px;
        }
        .el-container{
            width:100%;
            min-width:1000px;
            margin: 0px auto;
        }
        .el-header{
            background-color: #b3c0d1;
            color: #333;
            line-height:60px;
            height:60px;
            padding:0px;
        }
        .el-menu{
            padding:0 20px;
        }
        .el-menu .el-menu-item a{
            text-decoration: none;
            color: #fff;
        }
        .el-menu .el-menu-item a:hover{
            color:#ffd04b;
        }
    </style>
    <style>
        {% block style %}{% endblock %}
    </style>
</head>
<body>
    <div id="app">
        <el-container style="height:100%;border:1px solid #eee">
            <el-header style="">
                <el-menu class="el-menu-demo" mode="horizontal" background-color="#545c64"
                         text-color="#fff">
                    <el-menu-item style="display: inline-block;font-size:24px;margin-right:20px;"><span>护理管理信息系统</span></el-menu-item>
                    <el-menu-item><a href="{{ url_for('nurse.index') }}">首页</a></el-menu-item>
                    <el-menu-item><a href="{{ url_for('transfer.index') }}">人员调动</a></el-menu-item>
                    <el-menu-item><a>考试</a></el-menu-item>
                    <el-menu-item><a href="{{ url_for('train.index') }}">进修</a></el-menu-item>
                    <el-menu-item><a href="{{ url_for('leave.index') }}">休假</a></el-menu-item>
                    <el-submenu index="1" style='float:right;margin-right:50px;width:150px;text-align: left;'>
                        <template slot="title">{[ nickname ]}</template>
                        <el-menu-item index="1-1"><a href="" target="_blank">添加用户</a></el-menu-item>
                        <el-menu-item index="1-2"><a>修改密码</a></el-menu-item>
                        <el-menu-item index="1-3"><a href="/huli/logout">退出登陆</a></el-menu-item>
                    </el-submenu>
                </el-menu>
            </el-header>

            <el-main>
                {% block main %} {% endblock %}
            </el-main>
        </el-container>
    </div>
</body>
<script src="{{ url_for('static', filename='js/vue@2.6.10.js') }}"></script>
<script src="{{ url_for('static', filename='js/element-ui@2.12.0.js') }}"></script>
<script src="{{ url_for('static', filename='js/axios.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/tools.js') }}"></script>
<script>
    {% block script %}{% endblock %}
</script>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>护理管理信息系统</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/element-ui@2.12.0.css') }}">
    <style>
        *{
            margin: 0px;
            padding:0px;
        }
        .el-container{
            width:100%;
            min-width:1000px;
            margin: 0px auto;
        }
        .el-header{
            background-color: #b3c0d1;
            color: #333;
            line-height:60px;
            height:60px;
            padding:0px;
        }
        .el-menu{
            padding:0 20px;
        }
        .el-menu .el-menu-item a{
            text-decoration: none;
            color: #fff;
        }
        .el-menu .el-menu-item a:hover{
            color:#ffd04b;
        }
    </style>
</head>
<body>
    <div id="app">
        <el-container style="height:100%;border:1px solid #eee">
            <el-header style="">
                <el-menu class="el-menu-demo" mode="horizontal" background-color="#545c64"
                         text-color="#fff">
                    <el-menu-item style="display: inline-block;font-size:24px;margin-right:20px;"><span>护理管理信息系统</span></el-menu-item>
                    <el-menu-item><a href="{{ url_for('.index') }}">首页</a></el-menu-item>
                    <el-menu-item><a>人员调动</a></el-menu-item>
                    <el-menu-item><a>考试</a></el-menu-item>
                    <el-menu-item><a>进修</a></el-menu-item>
                    <el-menu-item><a>休假</a></el-menu-item>
                    <el-submenu index="1" style='float:right;margin-right:50px;width:150px;text-align: left;'>
                        <template slot="title">{[ nickname ]}</template>
                        <el-menu-item index="1-1"><a href="" target="_blank">添加用户</a></el-menu-item>
                        <el-menu-item index="1-2"><a>修改密码</a></el-menu-item>
                        <el-menu-item index="1-3"><a>退出登陆</a></el-menu-item>
                    </el-submenu>
                </el-menu>
            </el-header>

            <el-main>
                <div style="margin-bottom:20px;padding-left:20px;"><strong>护理人员列表</strong></div>
                <div class="content-tool">
                    <el-input v-model="search" placeholder="请输入搜索内容" style="display:inline-block;width:300px"></el-input>
                    <el-button type="primary" icon="el-icon-search" size="medium" @click="handleSearch">查询</el-button>
                    <el-button type="primary" icon="el-icon-plus" size="medium" @click="add_nurse">添加</el-button>
                    <el-button type="primary" icon="el-icon-delete" size="medium" @click="">删除</el-button>
                    <el-button type="primary" icon="el-icon-upload" size="medium" @click="">批量导入</el-button>
                    <el-button type="primary" icon="el-icon-refresh" size="medium" @click="refresh_table">刷新列表</el-button>
                </div>
                <el-table :data="page_data" :header-cell-style="{background:'#eef1f6',color:'#606266'}" v-loading="loading"
                     :default-sort="{prop: sort_prop, order: sort_order}" @sort-change="handleSortChange">
                    <el-table-column type="selection" width="60px" align="center"></el-table-column>
                    <el-table-column prop="emp_sn" label="工号" sortable="custom"></el-table-column>
                    <el-table-column prop="name" label="姓名" sortable="custom"></el-table-column>
                    <el-table-column prop="sex" label="性别" sortable="custom"></el-table-column>
                    <el-table-column prop="dept" label="科室" sortable="custom"></el-table-column>
                </el-table>
                <el-pagination
                    @size-change="handleSizeChange"
                    @current-change="handleCurrentChange"
                    :current-page="currentPage"
                    :page-sizes="[1, 2, 3, 4, 20]"
                    :page-size="pageSize"
                    layout="total,sizes,prev,pager,next,jumper"
                    :total="total"
                    :page-count="total_page"
                >
                </el-pagination>
            </el-main>
        </el-container>
    </div>
</body>
<script src="{{ url_for('static', filename='js/vue@2.6.10.js') }}"></script>
<script src="{{ url_for('static', filename='js/element-ui@2.12.0.js') }}"></script>
<script src="{{ url_for('static', filename='js/axios.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
<script>
    new Vue({
        el: '#app',
        delimiters: ['{[', ']}'],
        data: {
            search: '',
            nickname: JSON.parse(window.sessionStorage.getItem('user_info')).nickname,
            nurses: [],
            loading: true,
            sort_prop: 'emp_sn',
            sort_order: 'ascending',
            currentPage: 1,
            pageSize: 20,
            total: 0,
            total_page: 0,
            page_data: []
        },
        methods: {
            get_nurses(){
                axios({
                    method: 'get',
                    url: '{{ url_for('.get_nurses') }}'
                }).then(response => {
                    console.log(response)
                    if(response.data.code == 0){
                        this.nurses = response.data.data
                        this.page_data = this.nurses.slice(0, this.pageSize)
                        this.total = this.nurses.length
                        this.total_page = Math.ceil(this.total / this.pageSize)
                    }
                }).catch(response => {
                    this.$message.error('获取护理人员列表失败')
                })
                this.loading = false
            },
            handleSearch(){
                console.log(this.search)
                var filter_nurses = this.nurses.filter(data => {
                    return Object.keys(data).some(key => {
                        var search_result = String(data[key]).toLowerCase().indexOf(this.search)
                        console.log(search_result)
                        return  search_result > -1
                    })
                })
                console.log(filter_nurses)
                this.page_data = filter_nurses.slice(0, this.pageSize)
                this.total = filter_nurses.length
                this.total_page = Math.ceil(this.total / this.pageSize)
            },
            add_nurse(){
                this.get_nurse_data()
                var b = this.send_axios()
                console.log(b)
            },
            refresh_table(){
                this.loading = true
                axios({
                    method: 'get',
                    url: '{{ url_for('.get_nurses') }}'
                }).then(response => {
                    console.log(response)
                    if(response.data.code == 0){
                        this.nurses = response.data.data
                        /*this.currentPage = 1
                        this.page_data = this.nurses.slice(0, this.pageSize)
                        this.total = this.nurses.length
                        this.total_page = Math.ceil(this.total / this.pageSize)*/
                        this.handleCurrentChange(1)
                    }
                }).catch(response => {
                    this.$message.error('获取护理人员列表失败')
                })
                this.loading = false
            },
            handleSizeChange(val){
                total_page = Math.ceil(this.total / val)
                if(this.currentPage>total_page){
                    this.currentPage = total_page
                }
                this.pageSize = val
                this.page_data = this.nurses.slice((this.currentPage-1)*val, this.currentPage*val)
            },
            handleCurrentChange(val){
                this.currentPage = val
                this.page_data = this.nurses.slice((val-1)*this.pageSize, val*this.pageSize)
            },
            handleSortChange(column){
                var sort_prop = column.prop
                var sort_order = column.order
                if(sort_order == 'ascending'){
                    this.nurses.sort((a, b) => {return a[sort_prop] > b[sort_prop]})
                }else{
                    this.nurses.sort((a,b) => {return b[sort_prop] > a[sort_prop]})
                }
                this.page_data = this.nurses.slice((this.currentPage-1)*this.pageSize, this.currentPage*this.pageSize)
            }
        },
        mounted(){
            this.get_nurses()
        }
    })
</script>
</html>

app/templates/test.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <!-- import CSS -->
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
</head>
<body>
<div id="app">
    <div>{[ message ]}</div>
    <el-alert title="成功提示的文案" type="success" effect="dark" v-if="true"></el-alert>
    <el-button @click="visible = true">Button</el-button>
    <el-dialog :visible.sync="visible" title="Hello world">
        <p>Try Element</p>
    </el-dialog>
    <template>
        <el-table
                :data="tableData"
                style="width: 100%">
            <el-table-column
                    prop="date"
                    label="日期"
                    width="180">
            </el-table-column>
            <el-table-column
                    prop="name"
                    label="姓名"
                    width="180">
            </el-table-column>
            <el-table-column
                    prop="address"
                    label="地址">
                <template slot-scope="scope">
                    <a href="http://www.baidu.com">{[ scope.row.address ]}</a>
                </template>
            </el-table-column>
        </el-table>
    </template>

    <template>
        <el-tabs v-model="activeName" @tab-click="handleClick">
            <el-tab-pane label="用户管理" name="first">用户管理</el-tab-pane>
            <el-tab-pane label="配置管理" name="second">配置管理</el-tab-pane>
            <el-tab-pane label="角色管理" name="third">角色管理</el-tab-pane>
            <el-tab-pane label="定时任务补偿" name="fourth">定时任务补偿</el-tab-pane>
        </el-tabs>
    </template>
</div>
</body>
<!-- import Vue before Element -->
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<!-- import JavaScript -->
<script src="https://unpkg.com/element-ui/lib/index.js"></script>
<script>
    new Vue({
        el: '#app',
        delimiters: ['{[', ']}'],
        data: {
            visible: false,
            message: 'hello vue',
            tableData: [{
                date: '2016-05-02',
                name: '王小虎',
                address: '上海市普陀区金沙江路 1518 弄'
            }, {
                date: '2016-05-04',
                name: '王小虎',
                address: '上海市普陀区金沙江路 1517 弄'
            }, {
                date: '2016-05-01',
                name: '王小虎',
                address: '上海市普陀区金沙江路 1519 弄'
            }, {
                date: '2016-05-03',
                name: '王小虎',
                address: '上海市普陀区金沙江路 1516 弄'
            }],
            activeName: 'second'
        },
        methods: {
            handleClick: function(){},
        }
    })
</script>
</html>